#!/bin/bash

# Prompt for SSH password (this will be used for all SSH connections)
SSH_PASSWORD="y7Cv6i9/vacv"

# Optionally, you can set SSH options (e.g., to disable host key checking)
SSH_OPTS="-o StrictHostKeyChecking=no"

# Define iperf commands for server and client.
# This example assumes iperf3 is installed.
IPERF_CLIENT_CMD="iperf -c -u"

# Round 1
sshpass -p "$SSH_PASSWORD" ssh $SSH_OPTS node4@nf6.usc.edu "$IPERF_CLIENT_CMD 10.0.16.3 -p 5001 > log.out" &
sshpass -p "$SSH_PASSWORD" ssh $SSH_OPTS node4@nf7.usc.edu "$IPERF_CLIENT_CMD 10.0.16.3 -p 5002 > log.out" &
sshpass -p "$SSH_PASSWORD" ssh $SSH_OPTS node4@nf8.usc.edu "$IPERF_CLIENT_CMD 10.0.16.3 -p 5003 > log.out" &

sleep 15

sshpass -p "$SSH_PASSWORD" ssh $SSH_OPTS node4@nf5.usc.edu "$IPERF_CLIENT_CMD 10.0.17.3 -p 6001 > log.out" &
sshpass -p "$SSH_PASSWORD" ssh $SSH_OPTS node4@nf7.usc.edu "$IPERF_CLIENT_CMD 10.0.17.3 -p 6002 > log.out" &
sshpass -p "$SSH_PASSWORD" ssh $SSH_OPTS node4@nf8.usc.edu "$IPERF_CLIENT_CMD 10.0.17.3 -p 6003 > log.out" &

sleep 15

sshpass -p "$SSH_PASSWORD" ssh $SSH_OPTS node4@nf5.usc.edu "$IPERF_CLIENT_CMD 10.0.18.3 -p 7001 > log.out" &
sshpass -p "$SSH_PASSWORD" ssh $SSH_OPTS node4@nf6.usc.edu "$IPERF_CLIENT_CMD 10.0.18.3 -p 7002 > log.out" &
sshpass -p "$SSH_PASSWORD" ssh $SSH_OPTS node4@nf8.usc.edu "$IPERF_CLIENT_CMD 10.0.18.3 -p 7003 > log.out" &

sleep 15

sshpass -p "$SSH_PASSWORD" ssh $SSH_OPTS node4@nf5.usc.edu "$IPERF_CLIENT_CMD 10.0.19.3 -p 8001 > log.out" &
sshpass -p "$SSH_PASSWORD" ssh $SSH_OPTS node4@nf7.usc.edu "$IPERF_CLIENT_CMD 10.0.19.3 -p 8002 > log.out" &
sshpass -p "$SSH_PASSWORD" ssh $SSH_OPTS node4@nf6.usc.edu "$IPERF_CLIENT_CMD 10.0.19.3 -p 8003 > log.out" &